# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import sid_management_pb2 as sid__management__pb2


class SIDManagementStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddSID = channel.unary_unary(
        '/sidmanagement.SIDManagement/AddSID',
        request_serializer=sid__management__pb2.SIDMessage.SerializeToString,
        response_deserializer=sid__management__pb2.SIDMessageReply.FromString,
        )
    self.DelSID = channel.unary_unary(
        '/sidmanagement.SIDManagement/DelSID',
        request_serializer=sid__management__pb2.SIDMessage.SerializeToString,
        response_deserializer=sid__management__pb2.SIDMessageReply.FromString,
        )


class SIDManagementServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddSID(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DelSID(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SIDManagementServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddSID': grpc.unary_unary_rpc_method_handler(
          servicer.AddSID,
          request_deserializer=sid__management__pb2.SIDMessage.FromString,
          response_serializer=sid__management__pb2.SIDMessageReply.SerializeToString,
      ),
      'DelSID': grpc.unary_unary_rpc_method_handler(
          servicer.DelSID,
          request_deserializer=sid__management__pb2.SIDMessage.FromString,
          response_serializer=sid__management__pb2.SIDMessageReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sidmanagement.SIDManagement', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
